<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="MAIN" Id="{0d3e2942-f68d-453c-b4a1-c0350d874497}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	Lesson_2_2 : FN_2_2_Finite_State_Machine;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Lesson_2_2();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>